version: "3.9"
services:
  opera:
    restart: "unless-stopped"
    build:
      context: ./opera
      dockerfile: ${OPERA_DOCKERFILE}
      args:
        - BUILD_TARGET=${OPERA_SRC_BUILD_TARGET}
        - DOCKER_TAG=${OPERA_DOCKER_TAG}
    stop_grace_period: 3m
    image: opera:local
    volumes:
      - opera-ec-data:/var/lib/opera
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${EL_P2P_PORT}:${EL_P2P_PORT}/tcp
      - ${EL_P2P_PORT}:${EL_P2P_PORT}/udp
    labels:
      - traefik.enable=true
      - traefik.http.routers.opera.service=opera
      - traefik.http.routers.opera.entrypoints=websecure
      - traefik.http.routers.opera.rule=Host(`${EL_HOST}.${DOMAIN}`)
      - traefik.http.routers.opera.tls.certresolver=letsencrypt
      - traefik.http.routers.operalb.service=opera
      - traefik.http.routers.operalb.entrypoints=websecure
      - traefik.http.routers.operalb.rule=Host(`${EL_LB}.${DOMAIN}`)
      - traefik.http.routers.operalb.tls.certresolver=letsencrypt
      - traefik.http.services.opera.loadbalancer.server.port=${EL_RPC_PORT}
      - traefik.http.routers.operaws.service=operaws
      - traefik.http.routers.operaws.entrypoints=websecure
      - traefik.http.routers.operaws.rule=Host(`${EL_WS_HOST}.${DOMAIN}`)
      - traefik.http.routers.operaws.tls.certresolver=letsencrypt
      - traefik.http.routers.operawslb.service=operaws
      - traefik.http.routers.operawslb.entrypoints=websecure
      - traefik.http.routers.operawslb.rule=Host(`${EL_WS_LB}.${DOMAIN}`)
      - traefik.http.routers.operawslb.tls.certresolver=letsencrypt
      - traefik.http.services.operaws.loadbalancer.server.port=${EL_WS_PORT}
    environment:
      - GENESIS_FILE=${GENESIS_FILE}
      - LOG_LEVEL=${LOG_LEVEL}
    entrypoint:
      - docker-entrypoint.sh
      - opera
      - --http
      - --http.addr
      - 0.0.0.0
      - --http.vhosts=*
      - --http.api
      - web3,eth,net
      - --datadir
      - /var/lib/opera
      - --port
      - ${EL_P2P_PORT}
      - --http.port
      - ${EL_RPC_PORT}
      - --ws
      - --ws.addr
      - 0.0.0.0
      - --ws.port
      - ${EL_WS_PORT}
      - --ws.api
      - web3,eth,net
      - --gcmode
      - light
  set-prune-marker:
    profiles: ["tools"]
    image: alpine:latest
    user: "10001:10001"
    restart: "no"
    volumes:
      - opera-ec-data:/var/lib/opera
    entrypoint: ["/bin/sh","-c"]
    command: /bin/sh
volumes:
  opera-ec-data:
